.PHONY: install build run test deploy lint

# PORT := 9000
# NODE_VERSION := 4.5.0
# NODE_BIN := docker run -it --rm -v ${PWD}:/usr/src/app -w /usr/src/app node:${NODE_VERSION}

install: ## Install
	@ echo "Install"

build: ## Build
	@ echo "Build"

test: ## Test
	@ echo "Test"

watch: ## Watch
	@ echo "Watch"

run: ## Run
	@ echo "Run"

stop: ## Stop
	@ echo "Stop"

deploy: ## Deploy
	@ echo "Deploy"

lint: ## Lint
	@ echo "Lint"
